<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // contoh dummy data produk
        $products = [
            // Alat Tulis (10 produk)
            [
                'sku' => 'PRD001',
                'name' => 'Pensil 2B',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 3000,
                'cost_price' => 2000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD002',
                'name' => 'Buku Tulis 38 Lembar',
                'category_id' => 9,
                'tax_id' => 3,
                'sell_price' => 7000,
                'cost_price' => 5000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD003',
                'name' => 'Penghapus Putih',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 2500,
                'cost_price' => 1500,
                'unit' => 'pcs',
                'is_active' => false,
            ],
            [
                'sku' => 'PRD004',
                'name' => 'Spidol Permanent Hitam',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 8000,
                'cost_price' => 5500,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD005',
                'name' => 'Penggaris 30cm Besi',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 5000,
                'cost_price' => 3000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD006',
                'name' => 'Bolpoin Biru',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 2500,
                'cost_price' => 1500,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD007',
                'name' => 'Stabilo Warna Set 6',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 25000,
                'cost_price' => 18000,
                'unit' => 'set',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD008',
                'name' => 'Correction Tape',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 6000,
                'cost_price' => 4000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD009',
                'name' => 'Map Plastik Folio',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 3500,
                'cost_price' => 2000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD010',
                'name' => 'Gunting Kertas',
                'category_id' => 10,
                'tax_id' => 3,
                'sell_price' => 12000,
                'cost_price' => 8000,
                'unit' => 'pcs',
                'is_active' => false,
            ],

            // Elektronik (10 produk)
            [
                'sku' => 'PRD011',
                'name' => 'Kipas Angin Berdiri',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 250000,
                'cost_price' => 200000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD012',
                'name' => 'Lampu LED 12W',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 35000,
                'cost_price' => 25000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD013',
                'name' => 'Kabel USB Type-C 1m',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 45000,
                'cost_price' => 30000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD014',
                'name' => 'Power Bank 10000mAh',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 150000,
                'cost_price' => 100000,
                'unit' => 'pcs',
                'is_active' => false,
            ],
            [
                'sku' => 'PRD015',
                'name' => 'Charger HP 2A Fast Charging',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 55000,
                'cost_price' => 35000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD016',
                'name' => 'Earphone Bluetooth TWS',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 185000,
                'cost_price' => 130000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD017',
                'name' => 'Mouse Wireless',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 95000,
                'cost_price' => 65000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD018',
                'name' => 'Keyboard Gaming RGB',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 275000,
                'cost_price' => 200000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD019',
                'name' => 'Webcam HD 1080p',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 325000,
                'cost_price' => 250000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD020',
                'name' => 'Senter LED Rechargeable',
                'category_id' => 3,
                'tax_id' => 1,
                'sell_price' => 75000,
                'cost_price' => 50000,
                'unit' => 'pcs',
                'is_active' => true,
            ],

            // Peralatan Rumah Tangga (10 produk)
            [
                'sku' => 'PRD021',
                'name' => 'Tumbler Stainless 500ml',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 85000,
                'cost_price' => 60000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD022',
                'name' => 'Panci Stainless Steel 24cm',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 125000,
                'cost_price' => 90000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD023',
                'name' => 'Gelas Kaca Set 6pcs',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 75000,
                'cost_price' => 50000,
                'unit' => 'set',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD024',
                'name' => 'Sapu Ijuk + Gagang',
                'category_id' => 4,
                'tax_id' => 3,
                'sell_price' => 25000,
                'cost_price' => 15000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD025',
                'name' => 'Ember Plastik 20L',
                'category_id' => 4,
                'tax_id' => 3,
                'sell_price' => 35000,
                'cost_price' => 22000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD026',
                'name' => 'Piring Melamin Set 12pcs',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 95000,
                'cost_price' => 65000,
                'unit' => 'set',
                'is_active' => false,
            ],
            [
                'sku' => 'PRD027',
                'name' => 'Wajan Anti Lengket 28cm',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 145000,
                'cost_price' => 100000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD028',
                'name' => 'Teko Listrik 1.8L',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 165000,
                'cost_price' => 120000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD029',
                'name' => 'Rak Piring Stainless',
                'category_id' => 4,
                'tax_id' => 1,
                'sell_price' => 115000,
                'cost_price' => 80000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD030',
                'name' => 'Tempat Sampah Pedal 10L',
                'category_id' => 4,
                'tax_id' => 3,
                'sell_price' => 55000,
                'cost_price' => 38000,
                'unit' => 'pcs',
                'is_active' => true,
            ],

            // Makanan & Minuman (10 produk)
            [
                'sku' => 'PRD031',
                'name' => 'Kopi Arabica 250gr',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 65000,
                'cost_price' => 45000,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD032',
                'name' => 'Teh Celup Premium Box isi 25',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 25000,
                'cost_price' => 18000,
                'unit' => 'box',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD033',
                'name' => 'Mie Instan Goreng',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 3500,
                'cost_price' => 2500,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD034',
                'name' => 'Biskuit Cokelat 300gr',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 18000,
                'cost_price' => 12000,
                'unit' => 'pack',
                'is_active' => false,
            ],
            [
                'sku' => 'PRD035',
                'name' => 'Keripik Singkong Original 150gr',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 12000,
                'cost_price' => 8000,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD036',
                'name' => 'Susu UHT Cokelat 1L',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 18500,
                'cost_price' => 14000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD037',
                'name' => 'Minyak Goreng 1L',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 16000,
                'cost_price' => 13000,
                'unit' => 'btl',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD038',
                'name' => 'Gula Pasir 1kg',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 15000,
                'cost_price' => 12500,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD039',
                'name' => 'Kecap Manis Botol 600ml',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 14500,
                'cost_price' => 11000,
                'unit' => 'btl',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD040',
                'name' => 'Wafer Vanilla 350gr',
                'category_id' => 5,
                'tax_id' => 2,
                'sell_price' => 22000,
                'cost_price' => 16000,
                'unit' => 'pack',
                'is_active' => true,
            ],

            // Fashion & Aksesoris (10 produk)
            [
                'sku' => 'PRD041',
                'name' => 'Kaos Polos Cotton Combed',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 55000,
                'cost_price' => 35000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD042',
                'name' => 'Tas Ransel Kanvas',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 175000,
                'cost_price' => 120000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD043',
                'name' => 'Sepatu Sneakers Casual',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 285000,
                'cost_price' => 200000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD044',
                'name' => 'Topi Baseball Cap',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 45000,
                'cost_price' => 30000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD045',
                'name' => 'Kaos Kaki Panjang 3 Pasang',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 35000,
                'cost_price' => 22000,
                'unit' => 'pack',
                'is_active' => false,
            ],
            [
                'sku' => 'PRD046',
                'name' => 'Celana Jeans Pria',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 195000,
                'cost_price' => 140000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD047',
                'name' => 'Jaket Hoodie Polos',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 155000,
                'cost_price' => 110000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD048',
                'name' => 'Dompet Kulit Pria',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 85000,
                'cost_price' => 60000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD049',
                'name' => 'Ikat Pinggang Kulit',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 75000,
                'cost_price' => 50000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
            [
                'sku' => 'PRD050',
                'name' => 'Jam Tangan Digital Sport',
                'category_id' => 6,
                'tax_id' => 1,
                'sell_price' => 145000,
                'cost_price' => 100000,
                'unit' => 'pcs',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }
    }
}
